//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroonPOSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialIn
    {
        public int MaterialInId { get; set; }
        public string MaterialInNo { get; set; }
        public Nullable<int> MatInPurchaserId { get; set; }
        public string PurchaseItem { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public string Quality { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> Cartridge { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
