//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroonPOSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOut
    {
        public int MaterialOutId { get; set; }
        public string MaterialOutNo { get; set; }
        public Nullable<int> MatOutPartyId { get; set; }
        public Nullable<int> MaterialOutItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Description { get; set; }
        public Nullable<int> DCNumber { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
