//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroonPOSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int MaterialId { get; set; }
        public string MaterialNo { get; set; }
        public string PurchaserName { get; set; }
        public string PurchaseItem { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
