//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroonPOSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOutPayment
    {
        public int MaterialOutPayId { get; set; }
        public Nullable<int> MatOutPartyId { get; set; }
        public Nullable<bool> Debit { get; set; }
        public Nullable<bool> Credit { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> Payment { get; set; }
    }
}
