//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroonPOSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int UserRightsId { get; set; }
        public Nullable<int> AppUserId { get; set; }
        public string UserRoleName { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public string UserRoleCode { get; set; }
        public Nullable<int> AppFormId { get; set; }
        public string AppFormName { get; set; }
        public Nullable<bool> IsAdd { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsSelect { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
